# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:

  inputs:
    gitHubConnection: 'bigfathead'
    repositoryName: 'bigfathead/test123-'
    id: '1a2'
    comment: 'This is a test comment $(tt)'
  vmImage: ubuntu-latest



steps:
- script: echo Hello, world! $(tt)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    whoami
    sudo -s
  displayName: 'Run a multi-line script'
 


- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
      whoami
      pwd
      echo $HOME
      echo environment settings
      env
      mkdir dockerfiles
      ls -al
      docker --version
      df -h
      echo /opt dir
      ls -al /opt
      cat /etc/*release
      sudo -s 
      echo '{"data-root":"/home/vsts/work/1/s/dockerstorage"}' > /etc/docker/daemon.json
      cat /etc/docker/daemon.json
  displayName: 'run some stuff' 


- task: Cache@2
  inputs:
    key: 'docker | $(Agent.OS) |  ${{ parameters.WORKING_DIR }}'
    path: '/var/lib/docker'
       
- task: GitHubComment@0
  inputs:
    gitHubConnection: 'bigfathead'
    repositoryName: 'bigfathead/test123-'
    comment: |
      This is a test 2
      
      $(tt)
