# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:

  inputs:
    gitHubConnection: 'bigfathead'
    repositoryName: 'bigfathead/test123-'
    id: '1a2'
    comment: 'This is a test comment $(tt)'
  vmImage: ubuntu-latest



steps:
- script: tr
  displayName: 'Run a one-line script'

- script: |
    yum -y install sed
    echo "test" | sed 's/es//'
  displayName: 'Run a multi-line script'
 

