# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:

  inputs:
    gitHubConnection: 'bigfathead'
    repositoryName: 'bigfathead/test123-'
    id: '1a2'
    comment: 'This is a test comment $(tt)'
  vmImage: ubuntu-latest


steps:
- script: echo Hello, world! $(tt)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'bigfathead'
    repositoryName: 'bigfathead/test123-'
    comment: |
      This is a test 2
      
      $(tt)